### ISSUE TITLE
RPC Error in AddUI

### ISSUE THREAD

**Issue by AdriaanBoshoff** [umods/PlayerAdministration#1]
As soon as I type/padmin I get kicked with the following error:
![kjnjhgn](https://user-images.githubusercontent.com/16230645/38949602-23cdadb4-4343-11e8-8fc3-13b4c0279b25.png)

**Comment by thibmo** [comment]
Thanks for the report, will check it out.

**Comment by thibmo** [comment]
Fixed with 1.0.1
