### ISSUE TITLE
not connected users "blocking" the server

### ISSUE THREAD

**Issue by BlackFisch** [umods/PlayerAdministration#2]
When opening the control panel the server get's "occupied" by not connected users, also meaning that those UIDs cannot connect (Error message says they are already connected)

![Screenshot](https://user-images.githubusercontent.com/13716626/39083618-4d65244c-4567-11e8-8eaa-01d9ef7203e3.png)

**Comment by thibmo** [comment]
Correct, had this reported in private, too.
Trying to find what's causing this.

**Comment by thibmo** [comment]
Fixed in v1.0.3
Thanks for the report. :)
